# Generated by Django 2.2.4 on 2022-06-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Course',
        ),
    ]
